// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQGDsCp9AEmof5GYBOoMD1zYAcr5fpBas',
    appId: '1:944324164537:web:74983e25539d8ae3f45468',
    messagingSenderId: '944324164537',
    projectId: 'minimal-app-b1c88',
    authDomain: 'minimal-app-b1c88.firebaseapp.com',
    storageBucket: 'minimal-app-b1c88.firebasestorage.app',
    measurementId: 'G-FLKGE4J48H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQNj_-a2Z0SqxpJ5YsqNylQWqGqF9dPQE',
    appId: '1:944324164537:android:e18aa745d7482655f45468',
    messagingSenderId: '944324164537',
    projectId: 'minimal-app-b1c88',
    storageBucket: 'minimal-app-b1c88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD26p5BB5mT2ggWF02eCVuWCtojz8Zff-s',
    appId: '1:944324164537:ios:3a5de6009285b699f45468',
    messagingSenderId: '944324164537',
    projectId: 'minimal-app-b1c88',
    storageBucket: 'minimal-app-b1c88.firebasestorage.app',
    iosBundleId: 'com.example.minimalchat',
  );
}
